### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Sranshaft** [Fatburger3/btw-deco#1]
I've recently noticed some renewed interest on the BTW forum regarding this add-on and thought I'd share the fork I started a little while back. 

I've reorganized a lot of the code into separate modules and submodules. The modules follow the basic layout of Building, Decoration, Equipment, Food, Mechanical, Storage, Tweaks and World. The submodule further compartmentalize the code and allow the player to turn on and off features.

There's a basic API added to check for modules loaded, options, block / item IDs. I've added a rudimentary recipe API to commonly used recipes; brick, pillar, walls, stairs, etc. 

A lot of what I've done is simply code restructuring which should hopefully make additional updates and add-ons easier to implement so I hope you don't mind. I really enjoy playing with your add-on and wanted to expand on things while waiting for an update.

If you'd like to have a look, check here: https://github.com/Sranshaft/BTWDecoAddon

**Comment by cyates559** [comment]
Hello @Sranshaft. Holy shit, I'm sad that I didn't see this sooner. I just pushed a small update 5 mins ago.  This is awesome. I've been wanting to do this for a while I just haven't had any time.  Do you have a log of all the things you've changed?  I see some vanilla changes too.  Anyways, I'd be happy to merge our code and allow you to contribute more directly (as long as you aren't changing BTW code or anything).

One last thing, I started this project when I was about 16, so I was barely getting into programming.  Fast forward to today, I write Java at a professional level, and I must say, your java programming style in excellent.  I've wanted to refactor this code for years, and only recently have I started making small changes.  I am currently in the middle of moving into a new house, and when I'm all settled I plan on getting back into modding and BTW.  You've done the groundwork that will allow me to roll out many of the features I've wanted for a while.

**Comment by Sranshaft** [comment]
Go for mate! That's why i put it up on github. Let me push a couple commits first before you pull.

Vanilla code is mostly to do with the spyglass item and the beacon / potion effect being shown on screen similar to how it is in current versions. I don't think i changed anything else though it should be easy to find - i comment all changes to vanilla codebase. Search for added by btw deco' or something like that.

Thanks for the compliment but to be honest i absolutely hate writing java. I come from a C++ / C# myself so i tend just follow the guidelines I'm used to.

**Comment by Sranshaft** [comment]
Things should be good to go. Some things still need more testing and things like placing doors and merging slabs don't work quite right just yet but the framework is ready to go. 

Modules are easily addable by including them in the config file. Check how the others are included at the top of the file. The rest, I hope, is pretty straight forward.

**Comment by Sranshaft** [comment]
Oh, I meant to add that there's a need for vanilla-esque textures. I play using DerivationRPG and I've made all the textures in that style. If you, or know anyone, that wants to take a stab at making textures in the vanilla style fell free. If not, I can look into whipping some up.

**Comment by Sranshaft** [comment]
I've been quiet for some time but I've recently gotten back in to coding and have worked on getting the fork up to a release build. The fork has been updated version BTWMod4-ABCEEFABc of Better Than Wolves. Still need to add recipes for some of the blocks.

I'll be pushing what I've worked on to GitHub in a bit. Wanted to show a couple images of what I've added in the meantime.

https://1drv.ms/u/s!AmDNpSqjLjiJr_tuP8G1LU6MueQsYQ
https://1drv.ms/u/s!AmDNpSqjLjiJr_ttWw2-L_4j8KnPwQ
https://1drv.ms/u/s!AmDNpSqjLjiJr_tr4lwxNZmta6KPKQ
https://1drv.ms/u/s!AmDNpSqjLjiJr_tsvHxaeYkBpFsl6g

**Comment by cyates559** [comment]
I don't know if I can merge this in it's current state.  I like a lot of the stuff you have done, but if you want everyone else to see it, then it would really help if you broke it up into smaller changes and then made individual pull-requests instead of filing an issue.

**Comment by Sranshaft** [comment]
It'd be pretty hard to split this into separate pull requests. It's basically a complete rewrite. Could be used as a new base for further updates though. Let me know what your thoughts on this is.

**Comment by cyates559** [comment]
I'm sorry I just can't accept a complete rewrite.  If you make a pull request that updates my current code to your new config file system, that would be awesome...But I can't merge a pull request that changes every single line of every single file, or changes the name of all the files or the textures.

**Comment by Sranshaft** [comment]
That's fair. I'll continue my fork as a separate project. If there's any code you think you can use, feel free to use it.
